version: "3"
services:
  app:
    image: "751755577131.dkr.ecr.us-east-2.amazonaws.com/public-nameorigin:latest"
    ports:
      - "5000:5000"
    volumes:
      - /code
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-log-streaming
        awslogs-region: us-east-2
        awslogs-stream-prefix: flask-logs
    env_file:
      - ./apikey.env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - APIAPP_ENV=dev
      # - API_KEY_NAMES=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa # create a apikey.env file with your api key or uncomment with your key
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mex_polit_db
    ports:
      - '5432:5432'
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-log-streaming
        awslogs-region: us-east-2
        awslogs-stream-prefix: postgres-logs

    volumes:
      - postgresVol:/var/lib/postgresql/data
      # - ./database/init.sql/:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  postgresVol:


