"""improve estado model and gobernador

Revision ID: 10afcd89b0a3
Revises: 31f10accb774
Create Date: 2022-02-28 19:57:27.110411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10afcd89b0a3'
down_revision = '31f10accb774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estadosmextb', sa.Column('gobernador', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estadosmextb', 'gobernadoresmextb', ['gobernador'], ['id'])
    op.drop_constraint('gobernadoresmextb_estado_id_fkey', 'gobernadoresmextb', type_='foreignkey')
    op.drop_column('gobernadoresmextb', 'estado_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gobernadoresmextb', sa.Column('estado_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gobernadoresmextb_estado_id_fkey', 'gobernadoresmextb', 'estadosmextb', ['estado_id'], ['id'])
    op.drop_constraint(None, 'estadosmextb', type_='foreignkey')
    op.drop_column('estadosmextb', 'gobernador')
    # ### end Alembic commands ###
