"""change on db object dependency 3

Revision ID: 31f10accb774
Revises: 1c617b328b2a
Create Date: 2022-02-27 21:46:41.445228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f10accb774'
down_revision = '1c617b328b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadosmextb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fullnamestb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=128), nullable=False),
    sa.Column('lastName', sa.String(length=128), nullable=False),
    sa.Column('secondLastName', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('foundCountry1', sa.String(length=128), nullable=False),
    sa.Column('foundCountry1percent', sa.Float(), nullable=False),
    sa.Column('foundCountry2', sa.String(length=128), nullable=True),
    sa.Column('foundCountry2percent', sa.Float(), nullable=True),
    sa.Column('foundCountry3', sa.String(length=128), nullable=True),
    sa.Column('foundCountry3percent', sa.Float(), nullable=True),
    sa.Column('foundCountry4', sa.String(length=128), nullable=True),
    sa.Column('foundCountry4percent', sa.Float(), nullable=True),
    sa.Column('foundCountry5', sa.String(length=128), nullable=True),
    sa.Column('foundCountry5percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partialnamestb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('typeName', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('foundCountry1', sa.String(length=128), nullable=False),
    sa.Column('foundCountry1percent', sa.Float(), nullable=False),
    sa.Column('foundCountry2', sa.String(length=128), nullable=True),
    sa.Column('foundCountry2percent', sa.Float(), nullable=True),
    sa.Column('foundCountry3', sa.String(length=128), nullable=True),
    sa.Column('foundCountry3percent', sa.Float(), nullable=True),
    sa.Column('foundCountry4', sa.String(length=128), nullable=True),
    sa.Column('foundCountry4percent', sa.Float(), nullable=True),
    sa.Column('foundCountry5', sa.String(length=128), nullable=True),
    sa.Column('foundCountry5percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gobernadoresmextb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=128), nullable=True),
    sa.Column('nombres', sa.String(length=128), nullable=False),
    sa.Column('a_paterno', sa.String(length=128), nullable=False),
    sa.Column('a_materno', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estadosmextb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gobernadoresmextb')
    op.drop_table('partialnamestb')
    op.drop_table('fullnamestb')
    op.drop_table('estadosmextb')
    # ### end Alembic commands ###
