"""empty message

Revision ID: c382212b78ca
Revises: 
Create Date: 2022-04-12 03:09:45.211478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c382212b78ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fullnamestb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=128), nullable=False),
    sa.Column('lastName', sa.String(length=128), nullable=False),
    sa.Column('secondLastName', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('foundCountry1', sa.String(length=128), nullable=False),
    sa.Column('foundCountry1percent', sa.Float(), nullable=False),
    sa.Column('foundCountry2', sa.String(length=128), nullable=True),
    sa.Column('foundCountry2percent', sa.Float(), nullable=True),
    sa.Column('foundCountry3', sa.String(length=128), nullable=True),
    sa.Column('foundCountry3percent', sa.Float(), nullable=True),
    sa.Column('foundCountry4', sa.String(length=128), nullable=True),
    sa.Column('foundCountry4percent', sa.Float(), nullable=True),
    sa.Column('foundCountry5', sa.String(length=128), nullable=True),
    sa.Column('foundCountry5percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gobernadoresmextb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=128), nullable=True),
    sa.Column('nombres', sa.String(length=128), nullable=False),
    sa.Column('a_paterno', sa.String(length=128), nullable=False),
    sa.Column('a_materno', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partialnamestb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('typeName', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('foundCountry1', sa.String(length=128), nullable=False),
    sa.Column('foundCountry1percent', sa.Float(), nullable=False),
    sa.Column('foundCountry2', sa.String(length=128), nullable=True),
    sa.Column('foundCountry2percent', sa.Float(), nullable=True),
    sa.Column('foundCountry3', sa.String(length=128), nullable=True),
    sa.Column('foundCountry3percent', sa.Float(), nullable=True),
    sa.Column('foundCountry4', sa.String(length=128), nullable=True),
    sa.Column('foundCountry4percent', sa.Float(), nullable=True),
    sa.Column('foundCountry5', sa.String(length=128), nullable=True),
    sa.Column('foundCountry5percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadosmextb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=128), nullable=False),
    sa.Column('gobernador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gobernador'], ['gobernadoresmextb.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadosmextb')
    op.drop_table('partialnamestb')
    op.drop_table('gobernadoresmextb')
    op.drop_table('fullnamestb')
    # ### end Alembic commands ###
