"""add nullable references to delete them when needed

Revision ID: cfef20e62029
Revises: 10afcd89b0a3
Create Date: 2022-03-06 21:35:58.295670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfef20e62029'
down_revision = '10afcd89b0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('estadosmextb_gobernador_fkey', 'estadosmextb', type_='foreignkey')
    op.create_foreign_key(None, 'estadosmextb', 'gobernadoresmextb', ['gobernador'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estadosmextb', type_='foreignkey')
    op.create_foreign_key('estadosmextb_gobernador_fkey', 'estadosmextb', 'gobernadoresmextb', ['gobernador'], ['id'])
    # ### end Alembic commands ###
